window.HOMELINK_DATA = {
  exchangeRates: {
    KES: 1,
    USD: 0.00775,
    EUR: 0.0071,
    GBP: 0.0061
  },
  properties: [
    {
      id: 'hg-001',
      title: 'Skyline Furnished Apartment',
      location: 'Westlands, Nairobi',
      city: 'Nairobi',
      country: 'Kenya',
      transaction: 'Rent',
      type: 'Apartment',
      price: 185000,
      period: 'month',
      bedrooms: 3,
      bathrooms: 3,
      area: 165,
      status: 'Verified',
      featured: true,
      image: 'assets/images/penthouse-living.jpg',
      gallery: ['assets/images/penthouse-living.jpg','assets/images/modern-living-dining.jpg','assets/images/marble-kitchen.jpg','assets/images/master-bedroom.jpg'],
      amenities: ['Fully furnished', 'Backup generator', 'Gym', 'Pool', 'High-speed internet', '24/7 security'],
      description: 'A premium furnished residence positioned for executives, relocating families, and corporate clients who need a secure address close to business hubs, malls, schools, and healthcare facilities.',
      agent: 'Amina Properties',
      agentPhone: '+254 711 000 145'
    },
    {
      id: 'hg-002',
      title: 'Modern Family Townhouse',
      location: 'Runda, Nairobi',
      city: 'Nairobi',
      country: 'Kenya',
      transaction: 'Sale',
      type: 'Townhouse',
      price: 54500000,
      period: 'once',
      bedrooms: 5,
      bathrooms: 5,
      area: 390,
      status: 'Premium',
      featured: true,
      image: 'assets/images/family-home-exterior.jpg',
      gallery: ['assets/images/family-home-exterior.jpg','assets/images/hero-kitchen-dining.jpg','assets/images/white-bedroom.jpg','assets/images/bathtub-bathroom.jpg'],
      amenities: ['Private garden', 'DSQ', 'Solar water heating', 'Family lounge', 'Gated community', 'Parking for 4'],
      description: 'A spacious family home in a controlled gated environment, ideal for long-term ownership, diplomatic families, and high-value relocation clients seeking privacy and comfort.',
      agent: 'Prime Gate Realty',
      agentPhone: '+254 733 552 010'
    },
    {
      id: 'hg-003',
      title: 'Coastal Serviced Villa',
      location: 'Nyali, Mombasa',
      city: 'Mombasa',
      country: 'Kenya',
      transaction: 'Rent',
      type: 'Villa',
      price: 250000,
      period: 'month',
      bedrooms: 4,
      bathrooms: 4,
      area: 320,
      status: 'Verified',
      featured: true,
      image: 'assets/images/suburban-villa-exterior.jpg',
      gallery: ['assets/images/suburban-villa-exterior.jpg','assets/images/modern-living-dining.jpg','assets/images/glass-bathroom.jpg','assets/images/master-bedroom.jpg'],
      amenities: ['Beach access', 'Private pool', 'Housekeeping', 'Air conditioning', 'Security', 'Garden'],
      description: 'A refined coastal villa for short or medium-term relocation, executive stays, and holiday-family accommodation near schools, shopping, and leisure facilities.',
      agent: 'Coastline Homes',
      agentPhone: '+254 722 800 441'
    },
    {
      id: 'hg-004',
      title: 'Executive Studio Suite',
      location: 'Kilimani, Nairobi',
      city: 'Nairobi',
      country: 'Kenya',
      transaction: 'Rent',
      type: 'Studio',
      price: 78000,
      period: 'month',
      bedrooms: 1,
      bathrooms: 1,
      area: 58,
      status: 'Verified',
      featured: false,
      image: 'assets/images/hero-kitchen-dining.jpg',
      gallery: ['assets/images/hero-kitchen-dining.jpg','assets/images/white-bedroom.jpg','assets/images/double-sink-bathroom.jpg'],
      amenities: ['Furnished', 'Elevator', 'Smart TV', 'Rooftop terrace', 'Internet ready', 'CCTV'],
      description: 'Compact city living for professionals, consultants, and short-term relocation clients who need a clean, central, low-maintenance address.',
      agent: 'UrbanNest Kenya',
      agentPhone: '+254 700 019 154'
    },
    {
      id: 'hg-005',
      title: 'Corporate Office & Accommodation Tower',
      location: 'Upper Hill, Nairobi',
      city: 'Nairobi',
      country: 'Kenya',
      transaction: 'Rent',
      type: 'Commercial',
      price: 420000,
      period: 'month',
      bedrooms: 0,
      bathrooms: 4,
      area: 980,
      status: 'Commercial',
      featured: false,
      image: 'assets/images/business-towers.jpg',
      gallery: ['assets/images/business-towers.jpg','assets/images/city-apartments.jpg','assets/images/modern-living-dining.jpg'],
      amenities: ['Boardroom ready', 'Reception area', 'Power backup', 'Lift access', 'Parking', 'Security desk'],
      description: 'A practical commercial space for professional services, relocation operations, property teams, and corporate clients requiring a central Nairobi address.',
      agent: 'Industrial Link',
      agentPhone: '+254 734 901 233'
    },
    {
      id: 'hg-006',
      title: 'Lakeview Residential Plot',
      location: 'Kisumu, Milimani',
      city: 'Kisumu',
      country: 'Kenya',
      transaction: 'Sale',
      type: 'Land',
      price: 12500000,
      period: 'once',
      bedrooms: 0,
      bathrooms: 0,
      area: 505,
      status: 'Title Ready',
      featured: false,
      image: 'assets/images/modern-townhouses.jpg',
      gallery: ['assets/images/modern-townhouses.jpg','assets/images/family-home-exterior.jpg','assets/images/city-apartments.jpg'],
      amenities: ['Ready title', 'Access road', 'Utilities nearby', 'Residential zoning', 'Lake proximity'],
      description: 'A strategically positioned plot suitable for a residential home, investment property, or boutique serviced units in an established neighbourhood.',
      agent: 'Lakefront Realty',
      agentPhone: '+254 701 453 200'
    },
    {
      id: 'hg-007',
      title: 'Diaspora Investment Apartment',
      location: 'Kigali Heights, Rwanda',
      city: 'Kigali',
      country: 'Rwanda',
      transaction: 'Sale',
      type: 'Apartment',
      price: 26350000,
      period: 'once',
      bedrooms: 2,
      bathrooms: 2,
      area: 118,
      status: 'Cross-border',
      featured: true,
      image: 'assets/images/city-apartments.jpg',
      gallery: ['assets/images/city-apartments.jpg','assets/images/modern-living-dining.jpg','assets/images/marble-kitchen.jpg','assets/images/master-bedroom.jpg'],
      amenities: ['City views', 'Secure parking', 'Elevator', 'Gym access', 'Management office', 'Rental-ready'],
      description: 'A well-positioned cross-border investment unit designed for diaspora buyers and corporate clients seeking reliable regional real-estate options.',
      agent: 'Regional Homes Desk',
      agentPhone: '+250 788 200 300'
    },
    {
      id: 'hg-008',
      title: 'Relocation Family Residence',
      location: 'Mbezi Beach, Dar es Salaam',
      city: 'Dar es Salaam',
      country: 'Tanzania',
      transaction: 'Rent',
      type: 'House',
      price: 310000,
      period: 'month',
      bedrooms: 4,
      bathrooms: 3,
      area: 280,
      status: 'Corporate',
      featured: false,
      image: 'assets/images/suburban-villa-exterior.jpg',
      gallery: ['assets/images/suburban-villa-exterior.jpg','assets/images/modern-living-dining.jpg','assets/images/white-bedroom.jpg','assets/images/bathtub-bathroom.jpg'],
      amenities: ['Family compound', 'Staff room', 'Garden', 'Security', 'Close to beach', 'Corporate lease option'],
      description: 'A comfortable family residence for regional relocation clients, NGOs, executives, and corporate HR teams managing employee housing.',
      agent: 'East Africa Relocation Desk',
      agentPhone: '+255 744 550 100'
    },
    {
      id: 'hg-009',
      title: 'Karen Garden Residence',
      location: 'Karen, Nairobi',
      city: 'Nairobi',
      country: 'Kenya',
      transaction: 'Sale',
      type: 'House',
      price: 72000000,
      period: 'once',
      bedrooms: 5,
      bathrooms: 6,
      area: 520,
      status: 'Luxury',
      featured: true,
      image: 'assets/images/family-home-exterior.jpg',
      gallery: ['assets/images/family-home-exterior.jpg','assets/images/marble-kitchen.jpg','assets/images/master-bedroom.jpg','assets/images/glass-bathroom.jpg'],
      amenities: ['Mature garden', 'Private office', 'Guest wing', 'Solar backup', 'Gated estate', 'Staff quarters'],
      description: 'A high-value Nairobi residence for executives, embassy families, and long-term investors requiring a quiet, secure and spacious home environment.',
      agent: 'Karen Executive Homes',
      agentPhone: '+254 720 445 811'
    },
    {
      id: 'hg-010',
      title: 'Two-Bedroom Relocation Apartment',
      location: 'Lavington, Nairobi',
      city: 'Nairobi',
      country: 'Kenya',
      transaction: 'Rent',
      type: 'Apartment',
      price: 145000,
      period: 'month',
      bedrooms: 2,
      bathrooms: 2,
      area: 120,
      status: 'Move-in Ready',
      featured: false,
      image: 'assets/images/modern-living-dining.jpg',
      gallery: ['assets/images/modern-living-dining.jpg','assets/images/hero-kitchen-dining.jpg','assets/images/white-bedroom.jpg','assets/images/double-sink-bathroom.jpg'],
      amenities: ['Furnished option', 'Lift', 'Balcony', 'Backup power', 'Water storage', 'Secure parking'],
      description: 'A practical move-in-ready apartment for professionals and small families relocating to Nairobi with minimal setup delays.',
      agent: 'Lavington Living',
      agentPhone: '+254 712 771 982'
    },
    {
      id: 'hg-011',
      title: 'Airport Access Serviced Apartment',
      location: 'Entebbe Road, Kampala',
      city: 'Kampala',
      country: 'Uganda',
      transaction: 'Rent',
      type: 'Apartment',
      price: 195000,
      period: 'month',
      bedrooms: 3,
      bathrooms: 3,
      area: 150,
      status: 'Regional',
      featured: false,
      image: 'assets/images/penthouse-living.jpg',
      gallery: ['assets/images/penthouse-living.jpg','assets/images/marble-kitchen.jpg','assets/images/master-bedroom.jpg','assets/images/bathtub-bathroom.jpg'],
      amenities: ['Airport access', 'Housekeeping', 'Wi-Fi', 'Generator', 'Security', 'Serviced lease'],
      description: 'A regional serviced residence for consultants, expatriates and corporate travelers who need airport connectivity and professional property management.',
      agent: 'Regional Homes Desk',
      agentPhone: '+256 700 820 110'
    },
    {
      id: 'hg-012',
      title: 'Developer Off-Plan Townhomes',
      location: 'Kiambu Road, Nairobi',
      city: 'Kiambu',
      country: 'Kenya',
      transaction: 'Sale',
      type: 'Townhouse',
      price: 28500000,
      period: 'once',
      bedrooms: 4,
      bathrooms: 4,
      area: 240,
      status: 'Developer',
      featured: false,
      image: 'assets/images/colorful-townhouses.jpg',
      gallery: ['assets/images/colorful-townhouses.jpg','assets/images/modern-townhouses.jpg','assets/images/hero-kitchen-dining.jpg','assets/images/glass-bathroom.jpg'],
      amenities: ['Off-plan payment plan', 'Gated community', 'Clubhouse concept', 'Developer verified', 'Parking', 'Landscaped courts'],
      description: 'A developer-led townhome concept for buyers who want structured payment, verified project information and future family housing near Nairobi.',
      agent: 'Developer Relations Desk',
      agentPhone: '+254 701 330 909'
    }
  ],
  services: [
    { title: 'Airport Pickup & Arrival Support', description: 'Coordinate airport pickup, temporary accommodation, and first-day settling-in support for local and international movers.' },
    { title: 'Temporary Housing', description: 'Shortlist serviced apartments, furnished homes, and short-stay options while clients finalize permanent housing.' },
    { title: 'School & Neighbourhood Search', description: 'Support relocating families with school-area matching, neighbourhood guidance, commute considerations, and lifestyle fit.' },
    { title: 'Utilities & Move-in Setup', description: 'Track service requests for water, internet, power, cleaning, furnishing, and move-in readiness.' },
    { title: 'Moving & Logistics Coordination', description: 'Connect clients with movers, storage, packing, and relocation-service providers across supported markets.' },
    { title: 'Corporate Relocation Desk', description: 'Support HR teams, NGOs, and organisations with staff housing, lease tracking, viewings, and corporate accommodation.' }
  ]
};
